// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['bridge']['Bridge']['Connect'](arg1);
}

export function Disconnect() {
  return window['go']['bridge']['Bridge']['Disconnect']();
}

export function GetNetworks() {
  return window['go']['bridge']['Bridge']['GetNetworks']();
}

export function GetStatus() {
  return window['go']['bridge']['Bridge']['GetStatus']();
}

export function GetVirtualIP() {
  return window['go']['bridge']['Bridge']['GetVirtualIP']();
}

export function Login(arg1) {
  return window['go']['bridge']['Bridge']['Login'](arg1);
}
