// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bridge} from '../models';

export function Connect(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetNetworks():Promise<Array<bridge.NetworkInfo>>;

export function GetStatus():Promise<bridge.ConnectionStatus>;

export function GetVirtualIP():Promise<string>;

export function Login(arg1:string):Promise<bridge.LoginResult>;
