// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod omniedge {
    pub mod plugin {
        /// Logging functions available to plugins
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod logging {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            /// Log a trace-level message
            pub fn log_trace(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/logging@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-trace"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Log a debug-level message
            pub fn log_debug(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/logging@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-debug"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Log an info-level message
            pub fn log_info(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/logging@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-info"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Log a warn-level message
            pub fn log_warn(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/logging@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-warn"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Log an error-level message
            pub fn log_error(message: &str) -> () {
                unsafe {
                    let vec0 = message;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/logging@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "log-error"]
                        fn wit_import1(_: *mut u8, _: usize);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0.cast_mut(), len0) };
                }
            }
        }
        /// Configuration access for plugins
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod config {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            /// Get a string configuration value
            pub fn get_string(key: &str) -> Option<_rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/config@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "get-string"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                let bytes6 = _rt::Vec::from_raw_parts(
                                    l4.cast(),
                                    len6,
                                    len6,
                                );
                                _rt::string_lift(bytes6)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Get an integer configuration value
            pub fn get_int(key: &str) -> Option<i64> {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/config@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "get-int"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result5 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1.add(8).cast::<i64>();
                                l4
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result5
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Get a float configuration value
            pub fn get_float(key: &str) -> Option<f64> {
                unsafe {
                    #[repr(align(8))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/config@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "get-float"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result5 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1.add(8).cast::<f64>();
                                l4
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result5
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Get a boolean configuration value
            pub fn get_bool(key: &str) -> Option<bool> {
                unsafe {
                    #[repr(align(1))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 2]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2]);
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/config@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "get-bool"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result5 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = i32::from(*ptr1.add(1).cast::<u8>());
                                _rt::bool_lift(l4 as u8)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result5
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// List all configuration keys
            pub fn keys() -> _rt::Vec<_rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/config@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "keys"]
                        fn wit_import1(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0) };
                    let l2 = *ptr0.add(0).cast::<*mut u8>();
                    let l3 = *ptr0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base7 = l2;
                    let len7 = l3;
                    let mut result7 = _rt::Vec::with_capacity(len7);
                    for i in 0..len7 {
                        let base = base7
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e7 = {
                            let l4 = *base.add(0).cast::<*mut u8>();
                            let l5 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                            _rt::string_lift(bytes6)
                        };
                        result7.push(e7);
                    }
                    _rt::cabi_dealloc(
                        base7,
                        len7 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result8 = result7;
                    result8
                }
            }
        }
        /// Key-value store for plugin state persistence
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod kv_store {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[allow(unused_unsafe, clippy::all)]
            /// Set a value in the store
            pub fn set(key: &str, value: &[u8]) -> Result<(), _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = value;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/kv-store@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "set"]
                        fn wit_import3(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import3(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    unsafe {
                        wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2)
                    };
                    let l4 = i32::from(*ptr2.add(0).cast::<u8>());
                    let result8 = match l4 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l5 = *ptr2
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l6 = *ptr2
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len7 = l6;
                                let bytes7 = _rt::Vec::from_raw_parts(
                                    l5.cast(),
                                    len7,
                                    len7,
                                );
                                _rt::string_lift(bytes7)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result8
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Get a value from the store
            pub fn get(key: &str) -> Option<_rt::Vec<u8>> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/kv-store@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "get"]
                        fn wit_import2(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import2(ptr0.cast_mut(), len0, ptr1) };
                    let l3 = i32::from(*ptr1.add(0).cast::<u8>());
                    let result7 = match l3 {
                        0 => None,
                        1 => {
                            let e = {
                                let l4 = *ptr1
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l5 = *ptr1
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len6 = l5;
                                _rt::Vec::from_raw_parts(l4.cast(), len6, len6)
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result7
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Delete a value from the store
            pub fn delete(key: &str) -> bool {
                unsafe {
                    let vec0 = key;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/kv-store@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "delete"]
                        fn wit_import1(_: *mut u8, _: usize) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8, _: usize) -> i32 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import1(ptr0.cast_mut(), len0) };
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// List all keys in the store
            pub fn list_keys() -> _rt::Vec<_rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 2 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 2
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/kv-store@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "list-keys"]
                        fn wit_import1(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0) };
                    let l2 = *ptr0.add(0).cast::<*mut u8>();
                    let l3 = *ptr0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base7 = l2;
                    let len7 = l3;
                    let mut result7 = _rt::Vec::with_capacity(len7);
                    for i in 0..len7 {
                        let base = base7
                            .add(i * (2 * ::core::mem::size_of::<*const u8>()));
                        let e7 = {
                            let l4 = *base.add(0).cast::<*mut u8>();
                            let l5 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len6 = l5;
                            let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
                            _rt::string_lift(bytes6)
                        };
                        result7.push(e7);
                    }
                    _rt::cabi_dealloc(
                        base7,
                        len7 * (2 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result8 = result7;
                    result8
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Clear all values
            pub fn clear() -> Result<(), _rt::String> {
                unsafe {
                    #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                    #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                    struct RetArea(
                        [::core::mem::MaybeUninit<
                            u8,
                        >; 3 * ::core::mem::size_of::<*const u8>()],
                    );
                    let mut ret_area = RetArea(
                        [::core::mem::MaybeUninit::uninit(); 3
                            * ::core::mem::size_of::<*const u8>()],
                    );
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/kv-store@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "clear"]
                        fn wit_import1(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import1(_: *mut u8) {
                        unreachable!()
                    }
                    unsafe { wit_import1(ptr0) };
                    let l2 = i32::from(*ptr0.add(0).cast::<u8>());
                    let result6 = match l2 {
                        0 => {
                            let e = ();
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l3 = *ptr0
                                    .add(::core::mem::size_of::<*const u8>())
                                    .cast::<*mut u8>();
                                let l4 = *ptr0
                                    .add(2 * ::core::mem::size_of::<*const u8>())
                                    .cast::<usize>();
                                let len5 = l4;
                                let bytes5 = _rt::Vec::from_raw_parts(
                                    l3.cast(),
                                    len5,
                                    len5,
                                );
                                _rt::string_lift(bytes5)
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    };
                    result6
                }
            }
        }
        /// Time functions
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod time {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            /// Get current timestamp in milliseconds since Unix epoch
            pub fn now_ms() -> u64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/time@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "now-ms"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    ret as u64
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Get current timestamp in nanoseconds since Unix epoch
            pub fn now_ns() -> u64 {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "omniedge:plugin/time@1.0.0")]
                    unsafe extern "C" {
                        #[link_name = "now-ns"]
                        fn wit_import0() -> i64;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() -> i64 {
                        unreachable!()
                    }
                    let ret = unsafe { wit_import0() };
                    ret as u64
                }
            }
        }
        /// Types used by plugins
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            /// Plugin capability enumeration
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum Capability {
                EventHooks,
                Authentication,
                NetworkPolicy,
                DataTriage,
                QosEnforcement,
                PdmReporting,
                Compliance,
                UiWidgets,
            }
            impl ::core::fmt::Debug for Capability {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        Capability::EventHooks => {
                            f.debug_tuple("Capability::EventHooks").finish()
                        }
                        Capability::Authentication => {
                            f.debug_tuple("Capability::Authentication").finish()
                        }
                        Capability::NetworkPolicy => {
                            f.debug_tuple("Capability::NetworkPolicy").finish()
                        }
                        Capability::DataTriage => {
                            f.debug_tuple("Capability::DataTriage").finish()
                        }
                        Capability::QosEnforcement => {
                            f.debug_tuple("Capability::QosEnforcement").finish()
                        }
                        Capability::PdmReporting => {
                            f.debug_tuple("Capability::PdmReporting").finish()
                        }
                        Capability::Compliance => {
                            f.debug_tuple("Capability::Compliance").finish()
                        }
                        Capability::UiWidgets => {
                            f.debug_tuple("Capability::UiWidgets").finish()
                        }
                    }
                }
            }
            impl Capability {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> Capability {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => Capability::EventHooks,
                        1 => Capability::Authentication,
                        2 => Capability::NetworkPolicy,
                        3 => Capability::DataTriage,
                        4 => Capability::QosEnforcement,
                        5 => Capability::PdmReporting,
                        6 => Capability::Compliance,
                        7 => Capability::UiWidgets,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// VPN connection state
            #[derive(Clone)]
            pub enum ConnectionState {
                Disconnected,
                Authenticating,
                Authenticated,
                Joining(_rt::String),
                Connected(_rt::String),
            }
            impl ::core::fmt::Debug for ConnectionState {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        ConnectionState::Disconnected => {
                            f.debug_tuple("ConnectionState::Disconnected").finish()
                        }
                        ConnectionState::Authenticating => {
                            f.debug_tuple("ConnectionState::Authenticating").finish()
                        }
                        ConnectionState::Authenticated => {
                            f.debug_tuple("ConnectionState::Authenticated").finish()
                        }
                        ConnectionState::Joining(e) => {
                            f.debug_tuple("ConnectionState::Joining").field(e).finish()
                        }
                        ConnectionState::Connected(e) => {
                            f.debug_tuple("ConnectionState::Connected").field(e).finish()
                        }
                    }
                }
            }
            /// Peer information
            #[derive(Clone)]
            pub struct PeerInfo {
                pub public_key: _rt::String,
                pub virtual_ip: _rt::String,
                pub endpoint: Option<_rt::String>,
                pub last_handshake: u64,
                pub rx_bytes: u64,
                pub tx_bytes: u64,
            }
            impl ::core::fmt::Debug for PeerInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PeerInfo")
                        .field("public-key", &self.public_key)
                        .field("virtual-ip", &self.virtual_ip)
                        .field("endpoint", &self.endpoint)
                        .field("last-handshake", &self.last_handshake)
                        .field("rx-bytes", &self.rx_bytes)
                        .field("tx-bytes", &self.tx_bytes)
                        .finish()
                }
            }
            /// State change event
            #[derive(Clone)]
            pub struct StateChangeEvent {
                pub old_state: ConnectionState,
                pub new_state: ConnectionState,
                pub timestamp: u64,
                pub network_id: Option<_rt::String>,
            }
            impl ::core::fmt::Debug for StateChangeEvent {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("StateChangeEvent")
                        .field("old-state", &self.old_state)
                        .field("new-state", &self.new_state)
                        .field("timestamp", &self.timestamp)
                        .field("network-id", &self.network_id)
                        .finish()
                }
            }
            /// Network event type
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum NetworkEventType {
                Joined,
                Left,
                PeerAdded,
                PeerRemoved,
            }
            impl ::core::fmt::Debug for NetworkEventType {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        NetworkEventType::Joined => {
                            f.debug_tuple("NetworkEventType::Joined").finish()
                        }
                        NetworkEventType::Left => {
                            f.debug_tuple("NetworkEventType::Left").finish()
                        }
                        NetworkEventType::PeerAdded => {
                            f.debug_tuple("NetworkEventType::PeerAdded").finish()
                        }
                        NetworkEventType::PeerRemoved => {
                            f.debug_tuple("NetworkEventType::PeerRemoved").finish()
                        }
                    }
                }
            }
            impl NetworkEventType {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> NetworkEventType {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => NetworkEventType::Joined,
                        1 => NetworkEventType::Left,
                        2 => NetworkEventType::PeerAdded,
                        3 => NetworkEventType::PeerRemoved,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            /// Network event
            #[derive(Clone)]
            pub struct NetworkEvent {
                pub event_type: NetworkEventType,
                pub network_id: _rt::String,
                pub timestamp: u64,
            }
            impl ::core::fmt::Debug for NetworkEvent {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("NetworkEvent")
                        .field("event-type", &self.event_type)
                        .field("network-id", &self.network_id)
                        .field("timestamp", &self.timestamp)
                        .finish()
                }
            }
            /// Connection statistics
            #[repr(C)]
            #[derive(Clone, Copy)]
            pub struct ConnectionStats {
                pub rx_bytes: u64,
                pub tx_bytes: u64,
                pub rx_packets: u64,
                pub tx_packets: u64,
                pub connected_peers: u32,
                pub latency_ms: Option<f64>,
                pub uptime_seconds: u64,
            }
            impl ::core::fmt::Debug for ConnectionStats {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ConnectionStats")
                        .field("rx-bytes", &self.rx_bytes)
                        .field("tx-bytes", &self.tx_bytes)
                        .field("rx-packets", &self.rx_packets)
                        .field("tx-packets", &self.tx_packets)
                        .field("connected-peers", &self.connected_peers)
                        .field("latency-ms", &self.latency_ms)
                        .field("uptime-seconds", &self.uptime_seconds)
                        .finish()
                }
            }
            /// Plugin error
            #[derive(Clone)]
            pub struct PluginError {
                pub code: _rt::String,
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginError")
                        .field("code", &self.code)
                        .field("message", &self.message)
                        .finish()
                }
            }
            impl ::core::fmt::Display for PluginError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for PluginError {}
            /// Plugin manifest information
            #[derive(Clone)]
            pub struct PluginManifest {
                pub id: _rt::String,
                pub name: _rt::String,
                pub version: _rt::String,
                pub author: _rt::String,
                pub description: _rt::String,
                pub capabilities: _rt::Vec<Capability>,
            }
            impl ::core::fmt::Debug for PluginManifest {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("PluginManifest")
                        .field("id", &self.id)
                        .field("name", &self.name)
                        .field("version", &self.version)
                        .field("author", &self.author)
                        .field("description", &self.description)
                        .field("capabilities", &self.capabilities)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod omniedge {
        pub mod plugin {
            /// Base plugin interface - all plugins must implement this
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod base_plugin {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type PluginManifest = super::super::super::super::omniedge::plugin::types::PluginManifest;
                pub type PluginError = super::super::super::super::omniedge::plugin::types::PluginError;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_manifest_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::manifest();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let super::super::super::super::omniedge::plugin::types::PluginManifest {
                        id: id2,
                        name: name2,
                        version: version2,
                        author: author2,
                        description: description2,
                        capabilities: capabilities2,
                    } = result0;
                    let vec3 = (id2.into_bytes()).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    let vec4 = (name2.into_bytes()).into_boxed_slice();
                    let ptr4 = vec4.as_ptr().cast::<u8>();
                    let len4 = vec4.len();
                    ::core::mem::forget(vec4);
                    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
                    *ptr1
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr4.cast_mut();
                    let vec5 = (version2.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr1.add(5 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
                    *ptr1
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr5.cast_mut();
                    let vec6 = (author2.into_bytes()).into_boxed_slice();
                    let ptr6 = vec6.as_ptr().cast::<u8>();
                    let len6 = vec6.len();
                    ::core::mem::forget(vec6);
                    *ptr1.add(7 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
                    *ptr1
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr6.cast_mut();
                    let vec7 = (description2.into_bytes()).into_boxed_slice();
                    let ptr7 = vec7.as_ptr().cast::<u8>();
                    let len7 = vec7.len();
                    ::core::mem::forget(vec7);
                    *ptr1.add(9 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
                    *ptr1
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = ptr7.cast_mut();
                    let vec8 = capabilities2;
                    let len8 = vec8.len();
                    let layout8 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec8.len() * 1,
                        1,
                    );
                    let result8 = if layout8.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout8).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout8);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec8.into_iter().enumerate() {
                        let base = result8.add(i * 1);
                        {
                            *base.add(0).cast::<u8>() = (e.clone() as i32) as u8;
                        }
                    }
                    *ptr1
                        .add(11 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>() = len8;
                    *ptr1
                        .add(10 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>() = result8;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_manifest<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                    let l2 = *arg0
                        .add(2 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l3 = *arg0
                        .add(3 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l2, l3, 1);
                    let l4 = *arg0
                        .add(4 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l5 = *arg0
                        .add(5 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l4, l5, 1);
                    let l6 = *arg0
                        .add(6 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l7 = *arg0
                        .add(7 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l6, l7, 1);
                    let l8 = *arg0
                        .add(8 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l9 = *arg0
                        .add(9 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    _rt::cabi_dealloc(l8, l9, 1);
                    let l10 = *arg0
                        .add(10 * ::core::mem::size_of::<*const u8>())
                        .cast::<*mut u8>();
                    let l11 = *arg0
                        .add(11 * ::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base12 = l10;
                    let len12 = l11;
                    _rt::cabi_dealloc(base12, len12 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_load_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::on_load();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::omniedge::plugin::types::PluginError {
                                code: code2,
                                message: message2,
                            } = e;
                            let vec3 = (code2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (message2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr1
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_on_load<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_unload_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::on_unload();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let super::super::super::super::omniedge::plugin::types::PluginError {
                                code: code2,
                                message: message2,
                            } = e;
                            let vec3 = (code2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len3;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (message2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *ptr1
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len4;
                            *ptr1
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr4.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_on_unload<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                            let l3 = *arg0
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l4 = *arg0
                                .add(4 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l3, l4, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Return the plugin manifest
                    fn manifest() -> PluginManifest;
                    /// Called when the plugin is loaded
                    fn on_load() -> Result<(), PluginError>;
                    /// Called when the plugin is about to be unloaded
                    fn on_unload() -> Result<(), PluginError>;
                }
                #[doc(hidden)]
                macro_rules! __export_omniedge_plugin_base_plugin_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "omniedge:plugin/base-plugin@1.0.0#manifest")] unsafe extern "C"
                        fn export_manifest() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_manifest_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_omniedge:plugin/base-plugin@1.0.0#manifest")] unsafe
                        extern "C" fn _post_return_manifest(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_manifest::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "omniedge:plugin/base-plugin@1.0.0#on-load")] unsafe extern "C"
                        fn export_on_load() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_on_load_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_omniedge:plugin/base-plugin@1.0.0#on-load")] unsafe
                        extern "C" fn _post_return_on_load(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_on_load::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "omniedge:plugin/base-plugin@1.0.0#on-unload")] unsafe extern "C"
                        fn export_on_unload() -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_on_unload_cabi::<$ty > () } } #[unsafe (export_name =
                        "cabi_post_omniedge:plugin/base-plugin@1.0.0#on-unload")] unsafe
                        extern "C" fn _post_return_on_unload(arg0 : * mut u8,) { unsafe {
                        $($path_to_types)*:: __post_return_on_unload::<$ty > (arg0) } }
                        };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_omniedge_plugin_base_plugin_1_0_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 12 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 12
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
            /// Event plugin interface - react to VPN lifecycle events
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod event_plugin {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type StateChangeEvent = super::super::super::super::omniedge::plugin::types::StateChangeEvent;
                pub type PeerInfo = super::super::super::super::omniedge::plugin::types::PeerInfo;
                pub type NetworkEvent = super::super::super::super::omniedge::plugin::types::NetworkEvent;
                pub type ConnectionStats = super::super::super::super::omniedge::plugin::types::ConnectionStats;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_state_change_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: i32,
                    arg4: *mut u8,
                    arg5: usize,
                    arg6: i64,
                    arg7: i32,
                    arg8: *mut u8,
                    arg9: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    use super::super::super::super::omniedge::plugin::types::ConnectionState as V2;
                    let v2 = match arg0 {
                        0 => V2::Disconnected,
                        1 => V2::Authenticating,
                        2 => V2::Authenticated,
                        3 => {
                            let e2 = {
                                let len0 = arg2;
                                let bytes0 = _rt::Vec::from_raw_parts(
                                    arg1.cast(),
                                    len0,
                                    len0,
                                );
                                _rt::string_lift(bytes0)
                            };
                            V2::Joining(e2)
                        }
                        n => {
                            debug_assert_eq!(n, 4, "invalid enum discriminant");
                            let e2 = {
                                let len1 = arg2;
                                let bytes1 = _rt::Vec::from_raw_parts(
                                    arg1.cast(),
                                    len1,
                                    len1,
                                );
                                _rt::string_lift(bytes1)
                            };
                            V2::Connected(e2)
                        }
                    };
                    use super::super::super::super::omniedge::plugin::types::ConnectionState as V5;
                    let v5 = match arg3 {
                        0 => V5::Disconnected,
                        1 => V5::Authenticating,
                        2 => V5::Authenticated,
                        3 => {
                            let e5 = {
                                let len3 = arg5;
                                let bytes3 = _rt::Vec::from_raw_parts(
                                    arg4.cast(),
                                    len3,
                                    len3,
                                );
                                _rt::string_lift(bytes3)
                            };
                            V5::Joining(e5)
                        }
                        n => {
                            debug_assert_eq!(n, 4, "invalid enum discriminant");
                            let e5 = {
                                let len4 = arg5;
                                let bytes4 = _rt::Vec::from_raw_parts(
                                    arg4.cast(),
                                    len4,
                                    len4,
                                );
                                _rt::string_lift(bytes4)
                            };
                            V5::Connected(e5)
                        }
                    };
                    T::on_state_change(super::super::super::super::omniedge::plugin::types::StateChangeEvent {
                        old_state: v2,
                        new_state: v5,
                        timestamp: arg6 as u64,
                        network_id: match arg7 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len6 = arg9;
                                    let bytes6 = _rt::Vec::from_raw_parts(
                                        arg8.cast(),
                                        len6,
                                        len6,
                                    );
                                    _rt::string_lift(bytes6)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    });
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_peer_discovered_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: i64,
                    arg8: i64,
                    arg9: i64,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    T::on_peer_discovered(super::super::super::super::omniedge::plugin::types::PeerInfo {
                        public_key: _rt::string_lift(bytes0),
                        virtual_ip: _rt::string_lift(bytes1),
                        endpoint: match arg4 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len2 = arg6;
                                    let bytes2 = _rt::Vec::from_raw_parts(
                                        arg5.cast(),
                                        len2,
                                        len2,
                                    );
                                    _rt::string_lift(bytes2)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        last_handshake: arg7 as u64,
                        rx_bytes: arg8 as u64,
                        tx_bytes: arg9 as u64,
                    });
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_peer_disconnected_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: i32,
                    arg5: *mut u8,
                    arg6: usize,
                    arg7: i64,
                    arg8: i64,
                    arg9: i64,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    T::on_peer_disconnected(super::super::super::super::omniedge::plugin::types::PeerInfo {
                        public_key: _rt::string_lift(bytes0),
                        virtual_ip: _rt::string_lift(bytes1),
                        endpoint: match arg4 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len2 = arg6;
                                    let bytes2 = _rt::Vec::from_raw_parts(
                                        arg5.cast(),
                                        len2,
                                        len2,
                                    );
                                    _rt::string_lift(bytes2)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        last_handshake: arg7 as u64,
                        rx_bytes: arg8 as u64,
                        tx_bytes: arg9 as u64,
                    });
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_network_change_cabi<T: Guest>(
                    arg0: i32,
                    arg1: *mut u8,
                    arg2: usize,
                    arg3: i64,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg2;
                    let bytes0 = _rt::Vec::from_raw_parts(arg1.cast(), len0, len0);
                    T::on_network_change(super::super::super::super::omniedge::plugin::types::NetworkEvent {
                        event_type: super::super::super::super::omniedge::plugin::types::NetworkEventType::_lift(
                            arg0 as u8,
                        ),
                        network_id: _rt::string_lift(bytes0),
                        timestamp: arg3 as u64,
                    });
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_on_stats_update_cabi<T: Guest>(
                    arg0: i64,
                    arg1: i64,
                    arg2: i64,
                    arg3: i64,
                    arg4: i32,
                    arg5: i32,
                    arg6: f64,
                    arg7: i64,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::on_stats_update(super::super::super::super::omniedge::plugin::types::ConnectionStats {
                        rx_bytes: arg0 as u64,
                        tx_bytes: arg1 as u64,
                        rx_packets: arg2 as u64,
                        tx_packets: arg3 as u64,
                        connected_peers: arg4 as u32,
                        latency_ms: match arg5 {
                            0 => None,
                            1 => {
                                let e = arg6;
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                        uptime_seconds: arg7 as u64,
                    });
                }
                pub trait Guest {
                    /// Called when connection state changes
                    fn on_state_change(event: StateChangeEvent) -> ();
                    /// Called when a new peer is discovered
                    fn on_peer_discovered(peer: PeerInfo) -> ();
                    /// Called when a peer disconnects
                    fn on_peer_disconnected(peer: PeerInfo) -> ();
                    /// Called on network join/leave
                    fn on_network_change(event: NetworkEvent) -> ();
                    /// Called periodically with connection statistics
                    fn on_stats_update(stats: ConnectionStats) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_omniedge_plugin_event_plugin_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "omniedge:plugin/event-plugin@1.0.0#on-state-change")] unsafe
                        extern "C" fn export_on_state_change(arg0 : i32, arg1 : * mut u8,
                        arg2 : usize, arg3 : i32, arg4 : * mut u8, arg5 : usize, arg6 :
                        i64, arg7 : i32, arg8 : * mut u8, arg9 : usize,) { unsafe {
                        $($path_to_types)*:: _export_on_state_change_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) } }
                        #[unsafe (export_name =
                        "omniedge:plugin/event-plugin@1.0.0#on-peer-discovered")] unsafe
                        extern "C" fn export_on_peer_discovered(arg0 : * mut u8, arg1 :
                        usize, arg2 : * mut u8, arg3 : usize, arg4 : i32, arg5 : * mut
                        u8, arg6 : usize, arg7 : i64, arg8 : i64, arg9 : i64,) { unsafe {
                        $($path_to_types)*:: _export_on_peer_discovered_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) } }
                        #[unsafe (export_name =
                        "omniedge:plugin/event-plugin@1.0.0#on-peer-disconnected")]
                        unsafe extern "C" fn export_on_peer_disconnected(arg0 : * mut u8,
                        arg1 : usize, arg2 : * mut u8, arg3 : usize, arg4 : i32, arg5 : *
                        mut u8, arg6 : usize, arg7 : i64, arg8 : i64, arg9 : i64,) {
                        unsafe { $($path_to_types)*::
                        _export_on_peer_disconnected_cabi::<$ty > (arg0, arg1, arg2,
                        arg3, arg4, arg5, arg6, arg7, arg8, arg9) } } #[unsafe
                        (export_name =
                        "omniedge:plugin/event-plugin@1.0.0#on-network-change")] unsafe
                        extern "C" fn export_on_network_change(arg0 : i32, arg1 : * mut
                        u8, arg2 : usize, arg3 : i64,) { unsafe { $($path_to_types)*::
                        _export_on_network_change_cabi::<$ty > (arg0, arg1, arg2, arg3) }
                        } #[unsafe (export_name =
                        "omniedge:plugin/event-plugin@1.0.0#on-stats-update")] unsafe
                        extern "C" fn export_on_stats_update(arg0 : i64, arg1 : i64, arg2
                        : i64, arg3 : i64, arg4 : i32, arg5 : i32, arg6 : f64, arg7 :
                        i64,) { unsafe { $($path_to_types)*::
                        _export_on_stats_update_cabi::<$ty > (arg0, arg1, arg2, arg3,
                        arg4, arg5, arg6, arg7) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_omniedge_plugin_event_plugin_1_0_0_cabi;
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_event_plugin_world_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::omniedge::plugin::base_plugin::__export_omniedge_plugin_base_plugin_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::omniedge::plugin::base_plugin);
        $($path_to_types_root)*::
        exports::omniedge::plugin::event_plugin::__export_omniedge_plugin_event_plugin_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::omniedge::plugin::event_plugin);
    };
}
#[doc(inline)]
pub(crate) use __export_event_plugin_world_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:omniedge:plugin@1.0.0:event-plugin-world:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2043] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xf2\x0e\x01A\x02\x01\
A\x15\x01B\x06\x01@\x01\x07messages\x01\0\x04\0\x09log-trace\x01\0\x04\0\x09log-\
debug\x01\0\x04\0\x08log-info\x01\0\x04\0\x08log-warn\x01\0\x04\0\x09log-error\x01\
\0\x03\0\x1domniedge:plugin/logging@1.0.0\x05\0\x01B\x0f\x01ks\x01@\x01\x03keys\0\
\0\x04\0\x0aget-string\x01\x01\x01kx\x01@\x01\x03keys\0\x02\x04\0\x07get-int\x01\
\x03\x01ku\x01@\x01\x03keys\0\x04\x04\0\x09get-float\x01\x05\x01k\x7f\x01@\x01\x03\
keys\0\x06\x04\0\x08get-bool\x01\x07\x01ps\x01@\0\0\x08\x04\0\x04keys\x01\x09\x03\
\0\x1comniedge:plugin/config@1.0.0\x05\x01\x01B\x0e\x01p}\x01j\0\x01s\x01@\x02\x03\
keys\x05value\0\0\x01\x04\0\x03set\x01\x02\x01k\0\x01@\x01\x03keys\0\x03\x04\0\x03\
get\x01\x04\x01@\x01\x03keys\0\x7f\x04\0\x06delete\x01\x05\x01ps\x01@\0\0\x06\x04\
\0\x09list-keys\x01\x07\x01@\0\0\x01\x04\0\x05clear\x01\x08\x03\0\x1eomniedge:pl\
ugin/kv-store@1.0.0\x05\x02\x01B\x03\x01@\0\0w\x04\0\x06now-ms\x01\0\x04\0\x06no\
w-ns\x01\0\x03\0\x1aomniedge:plugin/time@1.0.0\x05\x03\x01B\x15\x01m\x08\x0beven\
t-hooks\x0eauthentication\x0enetwork-policy\x0bdata-triage\x0fqos-enforcement\x0d\
pdm-reporting\x0acompliance\x0aui-widgets\x04\0\x0acapability\x03\0\0\x01q\x05\x0c\
disconnected\0\0\x0eauthenticating\0\0\x0dauthenticated\0\0\x07joining\x01s\0\x09\
connected\x01s\0\x04\0\x10connection-state\x03\0\x02\x01ks\x01r\x06\x0apublic-ke\
ys\x0avirtual-ips\x08endpoint\x04\x0elast-handshakew\x08rx-bytesw\x08tx-bytesw\x04\
\0\x09peer-info\x03\0\x05\x01r\x04\x09old-state\x03\x09new-state\x03\x09timestam\
pw\x0anetwork-id\x04\x04\0\x12state-change-event\x03\0\x07\x01m\x04\x06joined\x04\
left\x0apeer-added\x0cpeer-removed\x04\0\x12network-event-type\x03\0\x09\x01r\x03\
\x0aevent-type\x0a\x0anetwork-ids\x09timestampw\x04\0\x0dnetwork-event\x03\0\x0b\
\x01ku\x01r\x07\x08rx-bytesw\x08tx-bytesw\x0arx-packetsw\x0atx-packetsw\x0fconne\
cted-peersy\x0alatency-ms\x0d\x0euptime-secondsw\x04\0\x10connection-stats\x03\0\
\x0e\x01r\x02\x04codes\x07messages\x04\0\x0cplugin-error\x03\0\x10\x01p\x01\x01r\
\x06\x02ids\x04names\x07versions\x06authors\x0bdescriptions\x0ccapabilities\x12\x04\
\0\x0fplugin-manifest\x03\0\x13\x03\0\x1bomniedge:plugin/types@1.0.0\x05\x04\x02\
\x03\0\x04\x0fplugin-manifest\x02\x03\0\x04\x0cplugin-error\x02\x03\0\x04\x0acap\
ability\x01B\x0c\x02\x03\x02\x01\x05\x04\0\x0fplugin-manifest\x03\0\0\x02\x03\x02\
\x01\x06\x04\0\x0cplugin-error\x03\0\x02\x02\x03\x02\x01\x07\x04\0\x0acapability\
\x03\0\x04\x01@\0\0\x01\x04\0\x08manifest\x01\x06\x01j\0\x01\x03\x01@\0\0\x07\x04\
\0\x07on-load\x01\x08\x04\0\x09on-unload\x01\x08\x04\0!omniedge:plugin/base-plug\
in@1.0.0\x05\x08\x02\x03\0\x04\x12state-change-event\x02\x03\0\x04\x09peer-info\x02\
\x03\0\x04\x0dnetwork-event\x02\x03\0\x04\x10connection-stats\x01B\x11\x02\x03\x02\
\x01\x09\x04\0\x12state-change-event\x03\0\0\x02\x03\x02\x01\x0a\x04\0\x09peer-i\
nfo\x03\0\x02\x02\x03\x02\x01\x0b\x04\0\x0dnetwork-event\x03\0\x04\x02\x03\x02\x01\
\x0c\x04\0\x10connection-stats\x03\0\x06\x01@\x01\x05event\x01\x01\0\x04\0\x0fon\
-state-change\x01\x08\x01@\x01\x04peer\x03\x01\0\x04\0\x12on-peer-discovered\x01\
\x09\x04\0\x14on-peer-disconnected\x01\x09\x01@\x01\x05event\x05\x01\0\x04\0\x11\
on-network-change\x01\x0a\x01@\x01\x05stats\x07\x01\0\x04\0\x0fon-stats-update\x01\
\x0b\x04\0\"omniedge:plugin/event-plugin@1.0.0\x05\x0d\x04\0(omniedge:plugin/eve\
nt-plugin-world@1.0.0\x04\0\x0b\x18\x01\0\x12event-plugin-world\x03\0\0\0G\x09pr\
oducers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x06\
0.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
