// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BridgeService exposes core OmniEdge functionality to the frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as api$0 from "../github.com/omniedgeio/omniedge-cli/pkg/api/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckExistingConnection checks if there's an existing VPN connection
 * @returns {$CancellablePromise<void>}
 */
export function CheckExistingConnection() {
    return $Call.ByID(4289202329);
}

/**
 * Connect initiates a VPN connection to the specified network
 * @param {string} networkID
 * @returns {$CancellablePromise<void>}
 */
export function Connect(networkID) {
    return $Call.ByID(4008425326, networkID);
}

/**
 * Disconnect terminates the current VPN connection
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(2404824402);
}

/**
 * GetLocalIP returns the local IP address
 * @returns {$CancellablePromise<string>}
 */
export function GetLocalIP() {
    return $Call.ByID(3741535526);
}

/**
 * GetLogos returns the app logo as base64
 * @returns {$CancellablePromise<string>}
 */
export function GetLogos() {
    return $Call.ByID(2079716152);
}

/**
 * GetNetworkDevices returns devices in a specific network
 * @param {string} networkID
 * @returns {$CancellablePromise<api$0.VirtualNetworkDeviceResponse[]>}
 */
export function GetNetworkDevices(networkID) {
    return $Call.ByID(2113861389, networkID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetNetworks returns the list of available virtual networks
 * @returns {$CancellablePromise<$models.NetworkInfo[]>}
 */
export function GetNetworks() {
    return $Call.ByID(2739368491).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetProfile returns the current user's profile
 * @returns {$CancellablePromise<api$0.ProfileResponse | null>}
 */
export function GetProfile() {
    return $Call.ByID(4245458193).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetStatus returns the current connection status
 * @returns {$CancellablePromise<string>}
 */
export function GetStatus() {
    return $Call.ByID(638355694);
}

/**
 * GetVirtualIP returns the virtual IP assigned to this device
 * @returns {$CancellablePromise<string>}
 */
export function GetVirtualIP() {
    return $Call.ByID(3906507406);
}

/**
 * Login authenticates with the OmniEdge API using a security key
 * @param {string} securityKey
 * @returns {$CancellablePromise<$models.LoginResult>}
 */
export function Login(securityKey) {
    return $Call.ByID(2916657013, securityKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * Ping measures latency to a target IP
 * @param {string} targetIP
 * @returns {$CancellablePromise<number>}
 */
export function Ping(targetIP) {
    return $Call.ByID(319741840, targetIP);
}

/**
 * SetApp sets the Wails app reference
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3250298835, app);
}

/**
 * SetAppIcon sets the app icon bytes
 * @param {string} icon
 * @returns {$CancellablePromise<void>}
 */
export function SetAppIcon(icon) {
    return $Call.ByID(2245979474, icon);
}

/**
 * SetSystemTray sets the system tray reference and icons for dynamic switching
 * @param {application$0.SystemTray | null} tray
 * @param {string} connected
 * @param {string} disconnected
 * @returns {$CancellablePromise<void>}
 */
export function SetSystemTray(tray, connected, disconnected) {
    return $Call.ByID(1035098297, tray, connected, disconnected);
}

// Private type creation functions
const $$createType0 = api$0.VirtualNetworkDeviceResponse.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.NetworkInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = api$0.ProfileResponse.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.LoginResult.createFrom;
