// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * LoginResult represents the result of a login attempt
 */
export class LoginResult {
    /**
     * Creates a new LoginResult instance.
     * @param {Partial<LoginResult>} [$$source = {}] - The source object to create the LoginResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LoginResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LoginResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LoginResult(/** @type {Partial<LoginResult>} */($$parsedSource));
    }
}

/**
 * NetworkInfo represents basic network information
 */
export class NetworkInfo {
    /**
     * Creates a new NetworkInfo instance.
     * @param {Partial<NetworkInfo>} [$$source = {}] - The source object to create the NetworkInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ip_range" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ip_range"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkInfo(/** @type {Partial<NetworkInfo>} */($$parsedSource));
    }
}
