#golang:mips64le
FROM mips64le/golang:1.18

# install golang
RUN apt-get update
RUN apt-get install -y wget make git autoconf automake build-essential pkg-config

RUN gcc --version
RUN go version
RUN go env
RUN uname -a
WORKDIR /app

COPY . .
ARG BUILD_ENV

ENV GOARCH=mips64le
ENV GOOS=linux
RUN go generate ./...
RUN BUILD_ENV=$BUILD_ENV make build