#golang:armv7
FROM arm32v7/golang:1.23-bookworm

# install build tools
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential libtool patch pkg-config

WORKDIR /app

COPY . .
RUN rm -f go.work

ENV GOWORK=off
ENV GOARCH=arm
RUN go generate ./...
RUN VERSION=$VERSION BUILD_ENV=$BUILD_ENV make build