#golang:arm64v8
FROM golang:buster@sha256:f60460ca6896db2269a4ec3fa25ddc0f3523706b2fae304b44693a7fd61fd5d5

# install golang
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential upx

WORKDIR /app

COPY . .
ARG BUILD_ENV

ENV GOARCH=arm64
RUN go generate ./...
RUN BUILD_ENV=$BUILD_ENV make build
RUN upx -9 -k ./out/omniedge
