#golang:ppc64le
FROM golang:buster@sha256:a1a70dddce2dfeea71e00c42b0255bef07da915f714a2d82b74040f97f060459

# install golang
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential upx

WORKDIR /app

COPY . .
ARG BUILD_ENV

ENV GOARCH=ppc64le
RUN go generate ./...
RUN BUILD_ENV=$BUILD_ENV make build
RUN upx -9 -k ./out/omniedge