#golang:arm64v8
FROM arm64v8/golang:1.21-bookworm

# install build tools
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential

WORKDIR /app

COPY . .
ARG BUILD_ENV

ENV GOARCH=arm64
RUN go generate ./...
RUN BUILD_ENV=$BUILD_ENV make build
