#golang:amd64
FROM golang:1.21-bookworm

# install build tools
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential

WORKDIR /app

COPY . .
ARG BUILD_ENV
ARG VERSION

ENV GOARCH=amd64
RUN go generate ./...
RUN VERSION=$VERSION BUILD_ENV=$BUILD_ENV make build
