#golang:386
FROM i386/golang:1.23-bookworm

# install golang
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential libtool patch pkg-config upx

WORKDIR /app

COPY . .
RUN rm -f go.work
ENV GOWORK=off
ENV GOARCH=386
ARG VERSION
ARG BUILD_ENV=prod
RUN go generate ./...
RUN VERSION=$VERSION BUILD_ENV=$BUILD_ENV make build
