#golang:armv7
FROM golang:buster@sha256:4c5a1dead04f13777610d1691ae6e4a376a2a1d938a6ef40d1f25815c3eb20d1

# install golang
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential upx

WORKDIR /app

COPY . .
ARG BUILD_ENV

ENV GOARCH=arm
RUN go generate ./...
RUN BUILD_ENV=$BUILD_ENV make build