FROM ubuntu:20.04

# Install all needed packages
RUN apt-get update && \
apt-get install -y wget git autoconf automake openssl autoconf build-essential libssl-dev zip wget g++-riscv64-linux-gnu gcc-riscv64-linux-gnu

WORKDIR /

RUN wget https://go.dev/dl/go1.18.4.linux-amd64.tar.gz
RUN rm -rf /usr/local/go && tar -C /usr/local -xzf go1.18.4.linux-amd64.tar.gz
RUN export PATH=$PATH:/usr/local/go/bin
RUN export GOOS=linux
RUN export GOARCH=riscv64
RUN export CGO_ENABLED=1
RUN export CC=riscv64-linux-gnu-gcc

WORKDIR /app

COPY . .
ARG BUILD_ENV

ENV GOARCH=riscv64
ENV CC=riscv64-linux-gnu-gcc
RUN go generate ./...
RUN BUILD_ENV=$BUILD_ENV make build-riscv64
