#golang:arm64v8
FROM arm64v8/golang:1.23-bookworm

# install build tools
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential libtool patch pkg-config

WORKDIR /app

COPY . .
RUN rm -f go.work

ENV GOWORK=off
ENV GOARCH=arm64
RUN go generate ./...
RUN VERSION=$VERSION BUILD_ENV=$BUILD_ENV make build
