#golang:mips64le
FROM golang:buster@sha256:09d3ddd6d8629773a05c3b1d484aeaf88469f735bcc12a56588413d43771d936

# install golang
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential libtool patch pkg-config

WORKDIR /app

COPY . .
RUN rm -f go.work
ENV GOWORK=off
ENV GOARCH=mips64le
RUN go generate ./...
RUN BUILD_ENV=$BUILD_ENV make build