#golang:s390x
FROM golang:buster@sha256:d952796475e3eb5a3ef5d3537f0e0b2da59ae75bc248e621c0c97695fec48363

# install golang
RUN apt update
RUN apt -y install wget make git autoconf automake build-essential upx

WORKDIR /app

COPY . .
ARG BUILD_ENV

ENV GOARCH=s390x
RUN go generate ./...
RUN BUILD_ENV=$BUILD_ENV make build