FROM ubuntu:20.04 AS build-env

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update
RUN apt-get install -y wget make curl git autoconf automake build-essential pkg-config openssl gzip libssl-dev zip upx

WORKDIR /

RUN curl -# -O https://dl.google.com/go/go1.4-bootstrap-20171003.tar.gz
RUN tar -zxvf go1.4-bootstrap-20171003.tar.gz && \
    cd go/src/ && \
    GOOS=linux GOARCH=amd64 ./make.bash
ENV export GOROOT_BOOTSTRAP=/go


WORKDIR /
RUN export GOROOT_BOOTSTRAP=/go && \
    mkdir golang && \
    wget https://go.dev/dl/go1.18.5.src.tar.gz && \
    mv go1.18.5.src.tar.gz golang/ && cd golang/ && \
    tar -xvf go1.18.5.src.tar.gz && \
    cd go/src/ && GOOS=linux GOARCH=mips GOMIPS=softfloat ./make.bash && \
    cd .. && ls pkg && ls bin

WORKDIR /app
COPY . .

WORKDIR /
RUN cp -r /golang/go /usr/local/ && \
    export GOROOT_BOOTSTRAP=/usr/local/go && \
    export GOROOT=/usr/local/go && \
    export GOBIN=$GOROOT/bin &&  \
    export GOPATH=/ && \
    export PATH=$PATH:$GOBIN:GOPATH/bin && \
    echo $PATH && go version && \
    cd / && \
    wget https://downloads.openwrt.org/releases/19.07.9/targets/ar71xx/generic/openwrt-sdk-19.07.9-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz && \
    tar -xf openwrt-sdk-19.07.9-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz && \ 
    mv openwrt-sdk-19.07.9-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64 openwrt_19.07.09-ar71xx && \
    rm go1.4-bootstrap-20171003.tar.gz && \
    rm openwrt-sdk-19.07.9-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz && \
    export CC=/openwrt_19.07.09-ar71xx/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/bin/mips-openwrt-linux-gcc && \ 
    export CXX=/openwrt_19.07.09-ar71xx/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/bin/mips-openwrt-linux-g++ && \
    export STAGING_DIR=/openwrt_19.07.09-ar71xx/staging_dir && \
    git clone -b dev https://github.com/yongqianme/omniedge-cli /app && \
    cd /app && CGO_ENABLED=1 GOOS=linux GOARCH=mips GOMIPS=softfloat BUILD_ENV=$BUILD_ENV make build && \
    upx -9 -k /app/out/omniedge && \
    zip -j /app/out/omniedge.zip /app/out/omniedge

FROM ubuntu:20.04
RUN mkdir /app
COPY --from=build-env /app/out/omniedge.zip /app/omniedge.zip
