FROM ubuntu:20.04 AS build-env

ENV CROSS_OPENWRT=openwrt
ARG BUILD_ENV
ARG VERSION

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update && apt -y install wget curl make git automake build-essential autoconf libtool patch pkg-config openssl gzip libssl-dev zip xz-utils upx

WORKDIR /

RUN wget -O go_bootstrap.tar.gz https://go.dev/dl/go1.22.10.linux-amd64.tar.gz && \
    tar -C / -xzf go_bootstrap.tar.gz && \
    mv /go /go_bootstrap && \
    rm go_bootstrap.tar.gz
ENV GOROOT_BOOTSTRAP=/go_bootstrap


WORKDIR /
RUN export GOROOT_BOOTSTRAP=/go_bootstrap && \
    mkdir golang && \
    wget https://go.dev/dl/go1.23.0.src.tar.gz && \
    mv go1.23.0.src.tar.gz golang/ && cd golang/ && \
    tar -xvf go1.23.0.src.tar.gz && \
    cd go/src/ && GOOS=linux GOARCH=mips GOMIPS=softfloat ./make.bash && \
    cd .. && ls pkg && ls bin

WORKDIR /app
COPY . .
RUN rm -f go.work

RUN cp -r /golang/go /usr/local/ && \
    export GOROOT_BOOTSTRAP=/usr/local/go && \
    export GOROOT=/usr/local/go && \
    export GOBIN=$GOROOT/bin &&  \
    export GOPATH=/ && \
    export GOWORK=off && \
    export PATH=$PATH:$GOBIN:$GOPATH/bin && \
    echo $PATH && go version && \
    cd / && \
    wget https://downloads.openwrt.org/releases/19.07.9/targets/ar71xx/generic/openwrt-sdk-19.07.9-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz && \
    tar -xf openwrt-sdk-19.07.9-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz && \
    mv openwrt-sdk-19.07.9-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64 openwrt_19.07.09-ar71xx && \
    rm -rf /go_bootstrap && \
    rm openwrt-sdk-19.07.9-ar71xx-generic_gcc-7.5.0_musl.Linux-x86_64.tar.xz && \
    export CC=/openwrt_19.07.09-ar71xx/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/bin/mips-openwrt-linux-gcc && \
    export CXX=/openwrt_19.07.09-ar71xx/staging_dir/toolchain-mips_24kc_gcc-7.5.0_musl/bin/mips-openwrt-linux-g++ && \
    export STAGING_DIR=/openwrt_19.07.09-ar71xx/staging_dir && \
    cd /app && cat internal/coren2n/make_n2n && CGO_ENABLED=1 GOOS=linux GOARCH=mips GOMIPS=softfloat VERSION=$VERSION BUILD_ENV=$BUILD_ENV make build && \
    upx -9 -k /app/out/omniedge && \
    zip -j /app/out/omniedge.zip /app/out/omniedge

FROM ubuntu:20.04
RUN mkdir -p /app/out
COPY --from=build-env /app/out/omniedge /app/out/omniedge
COPY --from=build-env /app/out/omniedge.zip /app/out/omniedge.zip

