#Cross-compile for arm64 using OpenWrt SDK on x86_64 host
FROM golang:1.23-bookworm

ARG OPENWRT_SDK=https://downloads.openwrt.org/releases/23.05.0/targets/rockchip/armv8/openwrt-sdk-23.05.0-rockchip-armv8_gcc-12.3.0_musl.Linux-x86_64.tar.xz

# install build tools
RUN apt update
RUN apt -y install wget make git automake build-essential autoconf libtool patch pkg-config openssl gzip libssl-dev zip xz-utils

RUN wget -O openwrt-sdk.tar.xz ${OPENWRT_SDK}
RUN xz -q -d openwrt-sdk.tar.xz && tar -xvf openwrt-sdk.tar
RUN mv -f openwrt-sdk-* openwrt-sdk

WORKDIR /app
COPY . .
RUN rm -f go.work
RUN /go/openwrt-sdk/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-gcc -v

ENV GOWORK=off
ARG BUILD_ENV
ARG VERSION

ENV CC=/go/openwrt-sdk/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-gcc
ENV CXX=/go/openwrt-sdk/staging_dir/toolchain-aarch64_generic_gcc-12.3.0_musl/bin/aarch64-openwrt-linux-g++
ENV CGO_ENABLED=1 
ENV GOARCH=arm64
ENV CROSS_OPENWRT=openwrt
RUN go generate ./...
RUN VERSION=$VERSION BUILD_ENV=$BUILD_ENV make build
RUN zip -j /app/out/omniedge.zip /app/out/omniedge
