#!/bin/sh
./autogen.sh

arch=$GOARCH
OS_V=$(uname)
CC_V=$CC
openwrt=$CROSS_OPENWRT

# https://github.com/ntop/n2n/issues/1013
# https://github.com/omniedgeio/omniedge/discussions/17


if [ "$openwrt" = 'openwrt' ]; then
    case $arch in  
		mips)
        	./configure --target=mips-openwrt-linux-musl --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"  
        	;;
		mipsle)
			./configure --target=mipsel-openwrt-linux-musl --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
			;;
		arm)
			./configure --target=arm-openwrt-linux-muslgnueabi --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
			;;
		arm64)
			./configure --target=aarch64-openwrt-linux-musl --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
			;;
		386)
			./configure --target=i386-pentium4-openwrt-linux-musl --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
			;;
		amd64|x86_64)
			./configure --target=x86-64-openwrt-linux-musl --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
			;;
    esac
else
    ./configure CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
if

if [ "$arch" = 'riscv64' ]; then
        ./configure --target=riscv64-unknow-linux-gnu --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
fi

if [ "$OS_V" = 'FreeBSD' ]; then
        gmake
else
        make
fi
