#!/bin/sh
./autogen.sh

arch=$GOARCH
OS_V=$(uname)

# https://github.com/ntop/n2n/issues/1013
# https://github.com/omniedgeio/omniedge/discussions/17


if [ "$arch" = 'mips' ]; then
        # for GL.iNet MIFI
        ./configure --host x86_64-linux-gnu --target=ar71xx-ath79
elif [ "$arch" = 'arm' ]; then
        # arm-openwrt-linux-muslgnueabi
        ./configure --target=arm-openwrt-linux-muslgnueabi --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
elif [ "$arch" = 'riscv64' ]; then
        ./configure --target=riscv64-unknow-linux-gnu --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
else
        ./configure CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
fi

if [ "$OS_V" = 'FreeBSD' ]; then
        gmake
else
        make
fi
