#!/bin/sh
./autogen.sh

arch=$GOARCH
OS_V=$(uname)
CC_V=$CC

# https://github.com/ntop/n2n/issues/1013
# https://github.com/omniedgeio/omniedge/discussions/17


if ["$CC_V"!='gcc']; then
        if [ "$arch" = 'mips' ]; then
                # for GL.iNet MIFI
                ./configure --target=mips-openwrt-linux-musl --host x86_64-linux-gnu
        elif [ "$arch" = 'arm' ]; then
                ./configure --target=arm-openwrt-linux-muslgnueabi --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
        elif [ "$arch" = 'arm64' ]; then
                ./configure --target=aarch64-openwrt-linux-musl --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
        elif [ "$arch" = '386' ]; then
                ./configure --target=i386-pentium4-openwrt-linux-musl --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
        elif [ "$arch" = 'amd64' ]; then
                ./configure --target=x86-64-openwrt-linux-musl --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
        elif [ "$arch" = 'riscv64' ]; then
                ./configure --target=riscv64-unknow-linux-gnu --host x86_64-linux-gnu CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
        fi
else
        ./configure CFLAGS="-DSKIP_MULTICAST_PEERS_DISCOVERY"
fi

if [ "$OS_V" = 'FreeBSD' ]; then
        gmake
else
        make
fi
