// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class IdentityResponse {
    /**
     * Creates a new IdentityResponse instance.
     * @param {Partial<IdentityResponse>} [$$source = {}] - The source object to create the IdentityResponse.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: string }}
             */
            this["metadata"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IdentityResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IdentityResponse}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField2_0($$parsedSource["metadata"]);
        }
        return new IdentityResponse(/** @type {Partial<IdentityResponse>} */($$parsedSource));
    }
}

export class ProfileResponse {
    /**
     * Creates a new ProfileResponse instance.
     * @param {Partial<ProfileResponse>} [$$source = {}] - The source object to create the ProfileResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("email" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["email"] = "";
        }
        if (!("picture" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["picture"] = "";
        }
        if (!("identities" in $$source)) {
            /**
             * @member
             * @type {(IdentityResponse | null)[]}
             */
            this["identities"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileResponse}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("identities" in $$parsedSource) {
            $$parsedSource["identities"] = $$createField4_0($$parsedSource["identities"]);
        }
        return new ProfileResponse(/** @type {Partial<ProfileResponse>} */($$parsedSource));
    }
}

export class VirtualNetworkDeviceResponse {
    /**
     * Creates a new VirtualNetworkDeviceResponse instance.
     * @param {Partial<VirtualNetworkDeviceResponse>} [$$source = {}] - The source object to create the VirtualNetworkDeviceResponse.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("virtual_ip" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["virtual_ip"] = "";
        }
        if (!("last_seen" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["last_seen"] = null;
        }
        if (!("online" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["online"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VirtualNetworkDeviceResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VirtualNetworkDeviceResponse}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VirtualNetworkDeviceResponse(/** @type {Partial<VirtualNetworkDeviceResponse>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = IdentityResponse.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = $Create.Array($$createType2);
